imports:
    - { resource: config.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    csrf_protection: true

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver: array
                query_cache_driver:    array

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
        console:
            type:  console

swiftmailer:
    disable_delivery: true

assetic:
    use_controller: false

pim_enrich:
    record_mails: true

parameters:
    max_products_category_removal: 20
    installer_data:       PimInstallerBundle:minimal
    upload_dir:           '%kernel.root_dir%/../var/cache/uploads/product'
    archive_dir:          '%kernel.root_dir%/../var/cache/archive'
    logs_dir:             '%kernel.logs_dir%'
    catalog_storage_dir:  '%kernel.root_dir%/../var/cache/file_storage/catalog'
    tmp_storage_dir:      '%kernel.root_dir%/../var/cache/tmp/pim/file_storage'
    upload_tmp_dir:       '%kernel.root_dir%/../var/cache/tmp/pim/upload_tmp_dir'
    env(BEHAT_URL): 'http://127.0.0.1/'
    behat_url: '%env(BEHAT_URL)%'
    env(BEHAT_TIMEOUT): 50000
    behat_timeout: '%env(BEHAT_TIMEOUT)%'
    env(BEHAT_SELENIUM_URL): 'http://127.0.0.1:4444/wd/hub'
    behat_selenium_url: '%env(BEHAT_SELENIUM_URL)%'
