parameters:
    pim_enrich.product_query_builder.filter.dummy.class: Pim\Bundle\EnrichBundle\ProductQueryBuilder\Filter\DummyFilter
    pim_enrich.query.elasticsearch.sorter.in_group.class: Pim\Bundle\EnrichBundle\Elasticsearch\Sorter\InGroupSorter
    pim_enrich.elasticsearch.from_size_cursor_factory.class: Pim\Bundle\EnrichBundle\Elasticsearch\FromSizeCursorFactory
    pim_enrich.query.product_and_product_model_query_builder.class: Pim\Bundle\EnrichBundle\ProductQueryBuilder\ProductAndProductModelQueryBuilder
    pim_enrich.datagrid.product_batch_size: 25

services:
    # Filters
    pim_enrich.product_query_builder.filter.dummy:
        class: '%pim_enrich.product_query_builder.filter.dummy.class%'
        arguments:
            - []
            - ['enabled', 'completeness']
            - ['ALL']
        tags:
            - { name: 'pim_catalog.elasticsearch.query.product_filter', priority: 30 }
            - { name: 'pim_catalog.elasticsearch.query.product_and_product_model_filter', priority: 30 }

    # Sorters
    pim_catalog.query.elasticsearch.sorter.in_group:
        class: '%pim_enrich.query.elasticsearch.sorter.in_group.class%'
        arguments:
            - '@pim_catalog.repository.group'
        tags:
            - { name: 'pim_catalog.elasticsearch.query.sorter', priority: 30 }

    # Services used by the products and product models' grid
    # here, products and product models should be gathered by the most top level product model
    pim_enrich.query.product_and_product_model_query_builder_from_size_factory:
        class: '%pim_catalog.query.elasticsearch.product_and_model_query_builder_factory.class%'
        arguments:
            - '%pim_enrich.query.product_and_product_model_query_builder.class%'
            - '@pim_enrich.query.product_query_builder_from_size_factory.with_product_and_product_model_from_size_cursor'

    akeneo.pim.enrichment.query.product_and_product_model_query_builder_from_size_factory.with_product_identifier_cursor:
        class: 'Akeneo\Pim\Enrichment\Bundle\Elasticsearch\ProductAndProductModelQueryBuilderFactory'
        arguments:
            - 'Pim\Bundle\EnrichBundle\ProductQueryBuilder\ProductAndProductModelQueryBuilder'
            - '@akeneo.pim.enrichment.query.product_query_builder_from_size_factory.with_product_identifier_cursor'

    pim_enrich.query.product_query_builder_from_size_factory.with_product_and_product_model_from_size_cursor:
        public: false
        class: '%pim_catalog.query.elasticsearch.product_query_builder_factory.class%'
        arguments:
            - '%pim_catalog.query.product_query_builder.class%'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.query.filter.product_and_product_model_registry'
            - '@pim_catalog.query.sorter.registry'
            - '@pim_enrich.factory.product_and_product_model_from_size_cursor'
            - '@pim_catalog.elasticsearch.product_query_builder_from_size_resolver'

    akeneo.pim.enrichment.query.product_query_builder_from_size_factory.with_product_identifier_cursor:
        public: false
        class: 'Akeneo\Pim\Enrichment\Bundle\Elasticsearch\ProductQueryBuilderFactory'
        arguments:
            - 'Akeneo\Pim\Enrichment\Component\Product\Query\ProductQueryBuilder'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.query.filter.product_and_product_model_registry'
            - '@pim_catalog.query.sorter.registry'
            - '@akeneo.pim.enrichment.factory.product_identifier_cursor'
            - '@pim_catalog.elasticsearch.product_query_builder_from_size_resolver'

    pim_enrich.factory.product_and_product_model_from_size_cursor:
        public: false
        class: '%pim_enrich.elasticsearch.from_size_cursor_factory.class%'
        arguments:
            - '@akeneo_elasticsearch.client.product_and_product_model'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.product_model'
            - '%pim_enrich.datagrid.product_batch_size%'
            - 'pim_catalog_product'

    akeneo.pim.enrichment.factory.product_identifier_cursor:
        public: false
        class: 'Akeneo\Pim\Enrichment\Bundle\Storage\ElasticsearchAndSql\ProductGrid\ProductAndProductModelIdentifierCursorFactory'
        arguments:
            - '@akeneo_elasticsearch.client.product_and_product_model'
            - 'pim_catalog_product'

    akeneo.pim.enrichment.product.grid.query.fetch_product_and_product_model_rows:
        class: 'Akeneo\Pim\Enrichment\Bundle\Storage\ElasticsearchAndSql\ProductGrid\FetchProductAndProductModelRows'
        arguments:
            - '@akeneo.pim.enrichment.product.grid.query.fetch_product_rows_from_identifiers'
            - '@akeneo.pim.enrichment.product.grid.query.fetch_product_model_rows_from_codes'

    akeneo.pim.enrichment.product.grid.query.fetch_product_model_rows_from_codes:
        class: 'Akeneo\Pim\Enrichment\Bundle\Storage\Sql\ProductGrid\FetchProductModelRowsFromCodes'
        arguments:
            - '@database_connection'
            - '@pim_catalog.factory.value_collection'

    akeneo.pim.enrichment.product.grid.query.fetch_product_rows_from_identifiers:
        class: 'Akeneo\Pim\Enrichment\Bundle\Storage\Sql\ProductGrid\FetchProductRowsFromIdentifiers'
        arguments:
            - '@database_connection'
            - '@pim_catalog.factory.value_collection'
